# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque # Tipe default untuk data arbitrer
stringData: # Gunakan stringData agar K8s otomatis encode ke base64
  API_KEY: "super-secret-key-12345"
  API_SECRET: "very-confidential-password!@#"
  # Contoh komentar: Jangan commit secret asli ke Git!
