# tls-secret.yaml
# CARA ALTERNATIF: Lebih mudah pakai 'kubectl create secret tls <nama> --cert=tls.crt --key=tls.key'
apiVersion: v1
kind: Secret
metadata:
  name: hello-k8s-tls-secret # Nama Secret yang akan dirujuk Ingress
type: kubernetes.io/tls # Tipe HARUS ini
data:
  # Nilai harus base64 encoded. Jalankan perintah berikut di terminal:
  # tls.crt: $(cat tls.crt | base64 | tr -d '\n')
  # tls.key: $(cat tls.key | base64 | tr -d '\n')
  # Lalu copy-paste hasilnya di bawah ini:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2gAwIBAgIJANJlUcQF6... (isi base64 cert Anda) UtLS0=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMzJYcW... (isi base64 key Anda) tLS0K
